USE [master]
GO

/****** Object:  Database [BitsBlog]    Script Date: 04/23/2012 23:47:48 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'BitsBlog')
DROP DATABASE [BitsBlog]
GO

USE [master]
GO

/****** Object:  Database [BitsBlog]    Script Date: 04/23/2012 23:47:48 ******/
CREATE DATABASE [BitsBlog] ON  PRIMARY 
( NAME = N'BitsBlog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\BitsBlog.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BitsBlog_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\BitsBlog_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BitsBlog] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BitsBlog].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BitsBlog] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BitsBlog] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BitsBlog] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BitsBlog] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BitsBlog] SET ARITHABORT OFF 
GO

ALTER DATABASE [BitsBlog] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BitsBlog] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BitsBlog] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BitsBlog] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BitsBlog] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BitsBlog] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BitsBlog] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BitsBlog] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BitsBlog] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BitsBlog] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BitsBlog] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BitsBlog] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BitsBlog] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BitsBlog] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BitsBlog] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BitsBlog] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BitsBlog] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BitsBlog] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BitsBlog] SET  READ_WRITE 
GO

ALTER DATABASE [BitsBlog] SET RECOVERY FULL 
GO

ALTER DATABASE [BitsBlog] SET  MULTI_USER 
GO

ALTER DATABASE [BitsBlog] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BitsBlog] SET DB_CHAINING OFF 
GO

